{{- if eq (include "vaultwarden.resourceType" .) "Deployment" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "vaultwarden.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: vaultwarden
    {{- include "vaultwarden.labels" . | nindent 4 }}
    {{- range $key, $value := .Values.commonLabels }}
    {{- printf "%s: %s" $key (tpl $value $ | quote) | nindent 4 }}
    {{- end }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: vaultwarden
      {{- include "vaultwarden.selectorLabels" . | nindent 6 }}
  {{- with .Values.strategy }}
  strategy:
    {{- . | toYaml | nindent 8 }}
  {{- end }}
  template:
    metadata:
      labels:
        app.kubernetes.io/component: vaultwarden
        {{- include "vaultwarden.selectorLabels" . | nindent 8 }}
      {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha1sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/secrets.yaml") . | sha1sum }}
        {{- with .Values.podAnnotations }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- include "vaultwarden.podSpec" . | nindent 6 }}
      volumes:
        {{- range $pvc := (fromYaml (include "vaultwarden.pvcSpec" .)).volumeClaimTemplates }}
        {{- $newName := printf "%s-%s-0" $pvc.metadata.name $.Release.Name }}
        - name: {{ $pvc.metadata.name }}
          persistentVolumeClaim:
            claimName: {{ $newName }}
        {{- end }}
{{- end }}