apiVersion: v2
name: vaultwarden
description: vaultwarden is an unofficial Bitwarden-compatible server written in Rust
keywords:
  - Rust
  - vaultwarden
sources:
  - https://github.com/guerzon/vaultwarden
  - https://github.com/dani-garcia/vaultwarden
appVersion: 1.25.0
maintainers:
  - name: Lester Guerzon
    email: lester@pidnull.io
    url: https://github.com/guerzon
version: 0.5.0
