domain: "https://vaultwarden.contoso.com"

tls:
  enabled: true
  certificateName: "vaultwarden-cert"

ingress:
  enabled: true
  hostname: vaultwarden.contoso.com
  class: "nginx"
  tls:
    enabled: true
    certificateName: "vaultwarden-cert"

persistence:
  enabled: true
  size: 5Gi
